# Generated by Django 4.2.3 on 2023-08-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rater',
            old_name='completed_survey',
            new_name='survey_date_taken',
        ),
    ]
