# Generated by Django 4.2.3 on 2023-09-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='slug',
        ),
    ]
