# Generated by Django 4.2.3 on 2023-08-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_rename_completed_survey_rater_survey_date_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rater',
            old_name='progress',
            new_name='survey_progress',
        ),
    ]
