# Generated by Django 4.2.3 on 2023-09-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_survey_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='survey_progress',
            field=models.CharField(choices=[('none', 'none'), ('done', 'done'), ('unfinished', 'unfinished')], default='none', max_length=250),
        ),
    ]
