# Generated by Django 4.2.3 on 2023-09-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_rater_survey_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='survey_progress',
            field=models.CharField(choices=[('unstarted', 'unstarted'), ('incomplete', 'incomplete'), ('finished', 'finished')], default='unstarted', max_length=250),
        ),
    ]
