# Generated by Django 4.2.3 on 2023-08-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_test_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
