# Generated by Django 4.2.3 on 2023-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='last_page_seen',
            field=models.SmallIntegerField(default=0),
        ),
    ]
