# Generated by Django 4.2.3 on 2023-08-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_rater_last_page_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='last_page_seen',
        ),
        migrations.AddField(
            model_name='rater',
            name='last_page_posted',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
