# Generated by Django 4.2.3 on 2023-08-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_remove_rater_last_page_seen_rater_last_page_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='last_page_posted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.page'),
        ),
    ]
