# Generated by Django 4.2.3 on 2023-08-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_alter_rater_last_page_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
