# Generated by Django 4.2.3 on 2023-08-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_page_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='last_page_posted',
        ),
        migrations.AddField(
            model_name='rater',
            name='posted_page_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
