# Generated by Django 4.2.3 on 2023-08-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_remove_rater_last_page_posted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='order',
            new_name='number',
        ),
    ]
