# Generated by Django 4.2.3 on 2023-09-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_rename_posted_page_number_rater_current_page_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rater',
            old_name='current_page_number',
            new_name='survey_page_number',
        ),
    ]
