# Generated by Django 4.2.3 on 2023-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_rename_current_page_number_rater_survey_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='survey_page_number',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
