# Generated by Django 4.2.3 on 2023-09-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_remove_page_survey_remove_survey_questions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='created',
            new_name='added',
        ),
    ]
