# Generated by Django 4.2.3 on 2023-09-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_response_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='data',
        ),
        migrations.AddField(
            model_name='response',
            name='multichoice',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
