# Generated by Django 4.2.3 on 2023-09-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_remove_response_data_response_multichoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='multichoice',
        ),
        migrations.AddField(
            model_name='response',
            name='multichoice',
            field=models.ManyToManyField(blank=True, related_name='multichoice', to='surveys.choice'),
        ),
    ]
