# Generated by Django 4.2.3 on 2023-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_remove_response_multichoice_response_multichoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='multichoice',
            field=models.ManyToManyField(blank=True, related_name='multichoices', to='surveys.choice'),
        ),
    ]
