# Generated by Django 4.2.3 on 2023-09-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_alter_response_multichoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='multichoice',
            new_name='multichoices',
        ),
    ]
