# Generated by Django 4.2.3 on 2023-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_rename_multichoice_response_multichoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='multichoices',
            field=models.ManyToManyField(blank=True, default=None, related_name='multichoices', to='surveys.choice'),
        ),
    ]
